const actionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  SELECT_PRODUCT: "SELECT_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
};
export default actionTypes;
